### ISSUE TITLE
Avatar Indicator in Playerlist

### ISSUE THREAD

**Issue by MrsJessica92** [loukylor/VRC-Mods#1]
Hey there,
I try out your new playerlist, which is pretty nice, as other mods are not able to show all and your's is. But I have a question, could you add maybe an indicator (I guess coloring the plattform could be cool) for the avatar - so like green for good and red für very poor etc. I like to use the playerlist also to check on events and such stuff, if other users are changing forbiddenwise the avatar to red and this could be then a really cool and helpfull extension of the mod.

greetings
Jessica92

**Comment by loukylor** [comment]
Added in 1.2.0
