### ISSUE TITLE
Avatar hider doesnt work currently.

### ISSUE THREAD

**Issue by SquidNeko** [loukylor/VRC-Mods#14]
Avatar hider doesnt work currently.

**Comment by MintLily** [comment]
That's painfully generic. Please, elaborate on your issue why why you think it doesn't work properly.

**Comment by SquidNeko** [comment]
Cause nothing of it works ingame. No matter what settings i put.

**Comment by loukylor** [comment]
Could you ensure you are on the latest version (1.2.4) and also check to make sure the mod itself is enabled. 

And by doesn't work do you mean that it's not hiding anyones avatars?

**Comment by SquidNeko** [comment]
I am on 1.2.6 yes and the mod is enabled.
Its not hiding anyone. Tried to toggle it on and off. Nothing.
I also tried to change distance. Still nothing.

Yea. Nobody's avatars are bieng hidden at all. No matter how far away i am.

**Comment by loukylor** [comment]
Also remember that AvatarHider requires VRCUtilityKit in order to function now. You can find a download in my Discord or in the releases section of the Github.

**Comment by SquidNeko** [comment]
Oh. I dont have the Utility.
So thats why im guessing.
