### ISSUE TITLE
Avatar Hider broken?

### ISSUE THREAD

**Issue by Rexios80** [loukylor/VRC-Mods#17]
VRC 1110

It's not hiding anything

**Comment by loukylor** [comment]
Are you sure you have [VRChatUtilityKit](https://api.vrcmg.com/v0/mods/231/VRChatUtilityKit.dll)?

AvatarHider doesn't work without it.

**Comment by Rexios80** [comment]
It used to work without it. Let's see how it goes.

**Comment by loukylor** [comment]
I had it require it to improve stability and make maintaining my mods easier.

**Comment by Rexios80** [comment]
Yep it works now. That's probably why a few of my mods broke lol. Thanks!
