### ISSUE TITLE
[Suggestion] Show a users username

### ISSUE THREAD

**Issue by fwenny** [loukylor/VRC-Mods#2]
Hiya. Was wondering if you could add an addition to UserInfoExtensions to show the users username, as it is shown on the website only (under the current persons nickname).

Additionally if possible, could you somehow add a toggle button to view their username on the nameplate, rather their current nickname?
That way I can select per person whether I wanna view their username or their nickname.

Thanks!

**Comment by loukylor** [comment]
I could add the username, but making is so you see username instead of current displayname would be really iffy. If any other mods mess with displayname it would cause issues. It's also not really in the spirit of the mod to mess with anything else other than the menus.

**Comment by fwenny** [comment]
Yeah I assumed you wouldnt want to, but just having a button to display it similar to Bio would also be great.

**Comment by loukylor** [comment]
Sorry was a bit slow, added this in 2.4.0 though
