### ISSUE TITLE
[PrivateInstanceIcon] I couldn't see that it was attached to the Favorites.

### ISSUE THREAD

**Issue by kazu0617** [loukylor/VRC-Mods#23]
I used the latest version of PrivateInstanceIcon (v1.0.0) and set only "hidePrivateInstances" to true in each config.
In the online list, the private people are properly cut out, but in the favorites list, the private people are also shown.

I will paste the log of when it was activated to see if it is the latest version.

```
[22:53:39.645] PrivateInstanceIcon v1.0.0
[22:53:39.647] by loukylor
[22:53:39.648] SHA256 Hash: 65f322258a2087a9049876319d1c664cdd2a0f9f61e4574dd1d1009773d1ecb1
[22:53:39.649] ------------------------------
```

**Comment by loukylor** [comment]
Ahhhh, yea. I completely forgot that favorite lists existed. I'll add a setting to affect the favorites lists as well and default it on.

**Comment by kazu0617** [comment]
Thank you. And... thank you for the fact that this mod has raised my QoL very much.

**Comment by loukylor** [comment]
Yep no problem. Was a quick mod to make anyway. Only like 2ish maybe 3 hours.
