### ISSUE TITLE
[PrivateInstanceIcon] Add total/hidden count to list title

### ISSUE THREAD

**Issue by Bluscream** [loukylor/VRC-Mods#24]
If you "unlist" private users it would be nice if you could see how many are hidden maybe like this:

![image](https://user-images.githubusercontent.com/3318223/129614242-d972fa8d-cd96-4fc7-bf6c-8b886c7256cb.png)

**Comment by Bluscream** [comment]
Or maybe if another mod already edits it (Though i only know about monkey mods that do that so far) just append `[1 private]` to the existing text per "hiding"

**Comment by kazu0617** [comment]
I have tried this feature. Once I turned off the setting value and made people visible, and then checked the checkbox to hide them again, the number of people was calculated incorrectly. i
