### ISSUE TITLE
cannot access VRChatUtilityKit menus

### ISSUE THREAD

**Issue by AngryMadRageFace** [loukylor/VRC-Mods#27]
i have the viewpoint tweaker and it said its settings are in a menu in THIS mods submenus but i have no idea where the heck that is. I have clicked all of the things and there are no things anywhere

**Comment by AngryMadRageFace** [comment]
im a dumbass

**Comment by loukylor** [comment]
LOL glad you figured it out

**Comment by AngryMadRageFace** [comment]
> 
> 
> LOL glad you figured it out

only to find another thing that bugs me

**Comment by loukylor** [comment]
uh viewpoint tweaker's menu is in UIX's menu not VRChatUtilityKit's

**Comment by AngryMadRageFace** [comment]
> 
> 
> uh viewpoint tweaker's menu is in UIX's menu not VRChatUtilityKit's

the menu is so low i didnt know i literally had to look down ingame just to see it lol. But now that i found it and tried using it, i think it would be better if i could manually enter in a number for XYZ coordinates for the vew point

**Comment by loukylor** [comment]
Make an issue on [knah's](https://github.com/knah/VRCMods) repo, that menu is part of UIX (one of his mods) not mine.
