### ISSUE TITLE
[PrivateInstanceIcon] Feature Request + Bug Report

### ISSUE THREAD

**Issue by Github-User-632345** [loukylor/VRC-Mods#29]
Please add the ability to see how many people are not hidden next to the hidden number.

On the current VRC build the option to hide people who are in Ask Me/Private does not function as intended and only shows the icons, hiding is bugged.

**Comment by loukylor** [comment]
Oh, huh ok lemme actually go and fix PII.

**Comment by loukylor** [comment]
I found the issue, was a small oversight by me. I'll push it once I figure out why it explodes and things people are on streamer mode.

**Comment by loukylor** [comment]
Addressed everything in 1.2.0
