### ISSUE TITLE
[PlayerList] Red "Q" when player is spoofing to be on quest while not in VR

### ISSUE THREAD

**Issue by Bluscream** [loukylor/VRC-Mods#36]
```
player.Method_Internal_get_APIUser_0().IsOnMobile && !player.field_Private_VRCPlayerApi_0.IsUserInVR()
```

**Comment by loukylor** [comment]
Would this be useful in any fashion. This would simply cause people to harass others and cause arguments. On top of that no one would know what the red Q meant even if I put it in both the readme and mod description.
