### ISSUE TITLE
[Feature Request] Show last logon time in 12-hour format in userinfoextentions, or have time format be configurable 

### ISSUE THREAD

**Issue by forever-and-a-day** [loukylor/VRC-Mods#4]
Please 24 hour time makes my brain hurt, would be nice for the time to either be in 12 hour format or have the time format be configurable in uiexpansionkit of a config file!

**Comment by loukylor** [comment]
Just get gud lol.

JK, I'll consider it, probably will make it configurable

**Comment by loukylor** [comment]
Added in 2.5.0
