### ISSUE TITLE
VRChat new UI update.

### ISSUE THREAD

**Issue by redsauce117** [loukylor/VRC-Mods#45]
Any ETA when your mods will be updated to support the new VRChat UI update?

**Comment by loukylor** [comment]
I've announced this in my server, but I will not be updating any mods except VRChatUtilityKit.

Any mods that are broken, will remain broken unless someone else updates them. As far as I know, the only one that has been updated is [InstanceHistory](https://github.com/Nirv-git/VRC-Mods).

**Comment by redsauce117** [comment]
Okay. Thank you for letting me know! (: Thank you for the hasty response. Love your work! xoxo
